// Small synthetic fixtures for each supported format. NOT real personal data.
// Positions are approximate GRCh37 coordinates for known seed SNPs.

export const FIXTURE_23ANDME = `# This data file generated by 23andMe at: Sun
# rsid\tchromosome\tposition\tgenotype
rs4680\t22\t19951271\tAG
rs1815739\t11\t66560624\tCT
rs9939609\t16\t53786615\tAA
rs6025\t1\t169519049\tGG
rs429358\t19\t45411941\tTT
rs7412\t19\t45412079\tCC
`;

export const FIXTURE_ANCESTRY = `#AncestryDNA raw data download
#
rsid\tchromosome\tposition\tallele1\tallele2
rs4680\t22\t19951271\tA\tG
rs1815739\t11\t66560624\tC\tC
rs1800562\t6\t26093141\tG\tA
`;

// MyHeritage: ## metadata, quoted CSV fields, low-pass method, and a no-call.
export const FIXTURE_MYHERITAGE = `##fileformat=MyHeritage
##source=MyHeritage
##method=Low-pass Whole Genome Sequencing
##
"RSID","CHROMOSOME","POSITION","RESULT"
"rs4680","22","19951271","AG"
"rs762551","15","75041917","AA"
"rs1061170","1","196659237","CC"
"rs10490924","10","124214448","--"
`;

// A genome that lacks APOE rs429358 (to exercise the indeterminate path).
export const FIXTURE_23ANDME_NO_APOE_KEY = `# 23andMe
# rsid\tchromosome\tposition\tgenotype
rs7412\t19\t45412079\tCC
rs4680\t22\t19951271\tGG
`;

export const FIXTURE_UNKNOWN = `name,value
foo,1
bar,2
`;
