import { describe, it, expect } from "vitest";
import {
  detectHealthReport,
  parseHealthReport,
} from "../src/parse/parseHealthReport";

const FIXTURE = `
health report

Table of Contents
1. Introduction
2. Summary
3. Genetic Results

This report is not valid for clinical or diagnostic use.  Page 1 of 50

Some intro about GWAS and genetic predisposition.
Complex diseases have two factors of influence: genetics and environmental factors.

This report is not valid for clinical or diagnostic use.  Page 9 of 50

GWAS Complex Diseases: Neurology

  Parkinson's disease

  Description of condition.                              Your genetic map
  Some more text.
                                                         Gene    SNP           Genotype
                                                         GBA     rs35749011    GG
                                                         NUCKS1  rs823118      CC
                                                         LRRK2   rs76904798    CC

  GWAS analysis

 What do your genetics tell us?

                   According to this study, you are less likely to
                   suffer from this disease than most of the
                   population.

 More information:
 www.ncbi.nlm.nih.gov/pubmed/25064009

This report is not valid for clinical or diagnostic use.  Page 32 of 50

GWAS Complex Diseases: Dermatology

  Vitiligo

  Description of vitiligo.                               Your genetic map
                                                         Gene    SNP           Genotype
                                                         TYR     rs1393350     AG
                                                         MHC     rs9271597     CT

  GWAS analysis

 What do your genetics tell us?

                   According to this study, you are more likely to
                   suffer from this disease than most of the
                   population.

 More information:
 www.ncbi.nlm.nih.gov/pubmed/27723757

This report is not valid for clinical or diagnostic use.  Page 33 of 50

Hereditary Diseases

  Cystic fibrosis

  A genetic disorder.                                    Your genetic map
                                                         Gene    SNP           Genotype
                                                         CFTR    rs75527207    GG

  Multivariate analysis

 What do your genetics tell us?

                   We have not detected any pathogenic mutations
                   but, since we only analyse a part of the gene,
                   you could have a pathogenic mutation.

This report is not valid for clinical or diagnostic use.  Page 200 of 50

Pharmacogenetics

  Warfarin

  Warfarin is an anticoagulant.                          Your genetic map
                                                         Gene    SNP           Genotype
                                                         VKORC1  rs9923231     CT

  Monovariate analysis

 What do your genetics tell us?

                   According to your genotype you have a greater predisposition
                   for the drug to have a harmful effect on you. Other non-analyzed
                   and non-genetic genetic factors may play a role.

This report is not valid for clinical or diagnostic use.  Page 250 of 50
`;

describe("detectHealthReport", () => {
  it("detects a GWAS health report", () => {
    expect(detectHealthReport(FIXTURE)).toBe(true);
  });

  it("rejects a 23andMe raw file", () => {
    const raw = `# This data file generated by 23andMe
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA`;
    expect(detectHealthReport(raw)).toBe(false);
  });
});

describe("parseHealthReport", () => {
  it("extracts condition findings from structured report text", () => {
    const result = parseHealthReport(FIXTURE);

    expect(result.totalConditions).toBeGreaterThanOrEqual(3);

    const parkinsons = result.findings.find(
      (f) => f.condition === "Parkinson's disease",
    );
    expect(parkinsons).toBeDefined();
    expect(parkinsons!.verdict).toBe("reduced");
    expect(parkinsons!.category).toBe("Neurology");
    expect(parkinsons!.methodology).toBe("GWAS");
    expect(parkinsons!.snps.length).toBeGreaterThan(0);
    expect(parkinsons!.snps[0].rsid).toBe("rs35749011");

    const vitiligo = result.findings.find(
      (f) => f.condition === "Vitiligo",
    );
    expect(vitiligo).toBeDefined();
    expect(vitiligo!.verdict).toBe("elevated");
    expect(vitiligo!.category).toBe("Dermatology");

    const warfarin = result.findings.find(
      (f) => f.condition === "Warfarin",
    );
    expect(warfarin).toBeDefined();
    expect(warfarin!.verdict).toBe("drug_harmful");
    expect(warfarin!.category).toBe("Pharmacogenetics");
    expect(warfarin!.methodology).toBe("monovariate");
  });

  it("excludes clear hereditary diseases", () => {
    const result = parseHealthReport(FIXTURE);
    const cf = result.findings.find(
      (f) => f.condition === "Cystic fibrosis",
    );
    expect(cf).toBeUndefined();
  });
});
