#!/usr/bin/env python3
"""
Generate synthetic genome sample files for genome-lens testing.
Output goes to samples/. Files contain NO real personal data.

Usage:
    python3 scripts/generate-samples.py
"""
import random
import os
import sys

CHROM_LENGTHS = {
    "1": 249250621, "2": 243199373, "3": 198022430, "4": 191154276,
    "5": 180915260, "6": 171115067, "7": 159138663, "8": 146364022,
    "9": 141213431, "10": 135534747, "11": 135006516, "12": 133851895,
    "13": 115169878, "14": 107349540, "15": 102531392, "16": 90354753,
    "17": 81195210,  "18": 78077248,  "19": 59128983,  "20": 63025520,
    "21": 48129895,  "22": 51304566,  "X": 155270560,
}
CHROM_ORDER = [str(i) for i in range(1, 23)] + ["X", "Y"]
CHROM_RANK  = {c: i for i, c in enumerate(CHROM_ORDER)}
CHROMS      = list(CHROM_LENGTHS.keys())
WEIGHTS     = [CHROM_LENGTHS[c] for c in CHROMS]
ALLELE_PAIRS = [("A","G"), ("C","T"), ("A","C"), ("G","T"), ("A","T"), ("C","G")]

# ── Knowledge-base rsids — present in every sample file ──────────────────────
# Format: (rsid, chrom, pos_grch37)
KB_POSITIONS = [
    ("rs4680",      "22", 19951271),
    ("rs762551",    "15", 75041917),
    ("rs1801133",   "1",  11856378),
    ("rs1801131",   "1",  11854476),
    ("rs6265",      "11", 27658369),
    ("rs1800497",   "11", 113270828),
    ("rs429358",    "19", 45411941),
    ("rs7412",      "19", 45412079),
    ("rs6025",      "1",  169519049),
    ("rs1800562",   "6",  26093141),
    ("rs1815739",   "11", 66560624),
    ("rs8192678",   "4",  23817854),
    ("rs9939609",   "16", 53786615),
    ("rs17782313",  "18", 55861362),
    ("rs634990",    "13", 20820493),
    ("rs1061170",   "1",  196659237),
    ("rs10490924",  "10", 124214448),
]

def random_genotype(rng: random.Random, a: str, b: str) -> tuple[str, str]:
    return rng.choices([(a, a), (a, b), (b, b)], weights=[0.30, 0.50, 0.20])[0]

def filler_snps(rng: random.Random, n: int, used: set, rsid_start: int):
    result = []
    counter = rsid_start
    for _ in range(n):
        chrom = rng.choices(CHROMS, weights=WEIGHTS)[0]
        while True:
            pos = rng.randint(10_000, CHROM_LENGTHS[chrom] - 10_000)
            if (chrom, pos) not in used:
                used.add((chrom, pos))
                break
        a, b = rng.choice(ALLELE_PAIRS)
        gt = random_genotype(rng, a, b)
        result.append((f"rs{counter}", chrom, pos, gt[0], gt[1]))
        counter += 1
    return result

def sort_snps(snps):
    return sorted(snps, key=lambda r: (CHROM_RANK.get(r[1], 99), r[2]))


# ── 23andMe format ────────────────────────────────────────────────────────────

def make_23andme(outdir: str):
    rng = random.Random(42)
    kb_rows = [
        ("rs4680",      "22", 19951271,   "A", "G"),
        ("rs762551",    "15", 75041917,   "A", "A"),
        ("rs1801133",   "1",  11856378,   "A", "G"),
        ("rs1801131",   "1",  11854476,   "T", "T"),
        ("rs6265",      "11", 27658369,   "C", "T"),
        ("rs1800497",   "11", 113270828,  "C", "T"),
        ("rs429358",    "19", 45411941,   "T", "T"),
        ("rs7412",      "19", 45412079,   "C", "C"),
        ("rs6025",      "1",  169519049,  "G", "G"),
        ("rs1800562",   "6",  26093141,   "G", "G"),
        ("rs1815739",   "11", 66560624,   "C", "T"),
        ("rs8192678",   "4",  23817854,   "G", "G"),
        ("rs9939609",   "16", 53786615,   "A", "T"),
        ("rs17782313",  "18", 55861362,   "C", "T"),
        ("rs634990",    "13", 20820493,   "C", "T"),
        ("rs1061170",   "1",  196659237,  "C", "C"),
        ("rs10490924",  "10", 124214448,  "G", "T"),
    ]
    used = {(r[1], r[2]) for r in kb_rows}
    filler = filler_snps(rng, 2500, used, 1_000_000_000)
    all_snps = sort_snps(
        [(r[0], r[1], r[2], r[3], r[4]) for r in kb_rows] + filler
    )

    lines = [
        "# This data file generated by 23andMe at: Fri Jun 14 00:00:00 2002",
        "# File is tab-separated.  Missing data is represented as --",
        "#",
        "# IMPORTANT: SYNTHETIC TEST FILE — fictional person, not real data.",
        "# Generated for genome-lens functional testing. rsids rs1000000000+ are fake.",
        "#",
        "# rsid\tchromosome\tposition\tgenotype",
    ]
    for rsid, chrom, pos, a1, a2 in all_snps:
        lines.append(f"{rsid}\t{chrom}\t{pos}\t{a1}{a2}")

    path = os.path.join(outdir, "synthetic-23andme.txt")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  23andMe:    {path}  ({len(all_snps):,} SNPs)")


# ── AncestryDNA format ────────────────────────────────────────────────────────

def make_ancestry(outdir: str):
    rng = random.Random(99)
    kb_rows = [
        ("rs4680",      "22", 19951271,   "A", "A"),
        ("rs762551",    "15", 75041917,   "A", "C"),
        ("rs1801133",   "1",  11856378,   "G", "G"),
        ("rs1801131",   "1",  11854476,   "G", "T"),
        ("rs6265",      "11", 27658369,   "C", "C"),
        ("rs1800497",   "11", 113270828,  "C", "T"),
        ("rs429358",    "19", 45411941,   "C", "T"),
        ("rs7412",      "19", 45412079,   "C", "C"),
        ("rs6025",      "1",  169519049,  "G", "G"),
        ("rs1800562",   "6",  26093141,   "G", "G"),
        ("rs1815739",   "11", 66560624,   "C", "C"),
        ("rs8192678",   "4",  23817854,   "A", "G"),
        ("rs9939609",   "16", 53786615,   "A", "A"),
        ("rs17782313",  "18", 55861362,   "T", "T"),
        ("rs634990",    "13", 20820493,   "C", "C"),
        ("rs1061170",   "1",  196659237,  "C", "T"),
        ("rs10490924",  "10", 124214448,  "G", "G"),
    ]
    used = {(r[1], r[2]) for r in kb_rows}
    filler = filler_snps(rng, 1800, used, 2_000_000_000)
    all_snps = sort_snps(
        [(r[0], r[1], r[2], r[3], r[4]) for r in kb_rows] + filler
    )

    lines = [
        "#AncestryDNA raw data download",
        "#",
        "# IMPORTANT: SYNTHETIC TEST FILE — fictional person, not real data.",
        "# Generated for genome-lens functional testing. rsids rs2000000000+ are fake.",
        "#",
        "rsid\tchromosome\tposition\tallele1\tallele2",
    ]
    for rsid, chrom, pos, a1, a2 in all_snps:
        lines.append(f"{rsid}\t{chrom}\t{pos}\t{a1}\t{a2}")

    path = os.path.join(outdir, "synthetic-ancestry.txt")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  AncestryDNA:{path}  ({len(all_snps):,} SNPs)")


# ── MyHeritage (Low-pass WGS) format ─────────────────────────────────────────

def make_myheritage(outdir: str):
    rng = random.Random(77)
    kb_rows = [
        ("rs4680",      "22", 19951271,   "AG"),
        ("rs762551",    "15", 75041917,   "AC"),
        ("rs1801133",   "1",  11856378,   "GG"),
        ("rs1801131",   "1",  11854476,   "GT"),
        ("rs6265",      "11", 27658369,   "CC"),
        ("rs1800497",   "11", 113270828,  "CT"),
        ("rs429358",    "19", 45411941,   "CT"),
        ("rs7412",      "19", 45412079,   "CC"),
        ("rs6025",      "1",  169519049,  "GG"),
        ("rs1800562",   "6",  26093141,   "GG"),
        ("rs1815739",   "11", 66560624,   "CC"),
        ("rs8192678",   "4",  23817854,   "AG"),
        ("rs9939609",   "16", 53786615,   "AA"),
        ("rs17782313",  "18", 55861362,   "TT"),
        ("rs634990",    "13", 20820493,   "CC"),
        ("rs1061170",   "1",  196659237,  "CT"),
        ("rs10490924",  "10", 124214448,  "GG"),
    ]

    used = {(r[1], r[2]) for r in kb_rows}
    filler_raw = filler_snps(rng, 2200, used, 3_000_000_000)
    filler_with_nocalls = []
    for rsid, chrom, pos, a1, a2 in filler_raw:
        gt = "--" if rng.random() < 0.02 else f"{a1}{a2}"
        filler_with_nocalls.append((rsid, chrom, pos, gt))

    kb_tuples = [(r[0], r[1], r[2], r[3]) for r in kb_rows]
    all_snps_raw = sort_snps(
        [(r[0], r[1], r[2], r[3], r[3]) for r in kb_rows]
        + [(r[0], r[1], r[2], r[3], r[3]) for r in filler_with_nocalls]
    )

    lines = [
        '##fileformat=MyHeritage',
        '##source=MyHeritage',
        '##method=Low-pass Whole Genome Sequencing',
        '##build=GRCh37',
        '##',
        '## IMPORTANT: SYNTHETIC TEST FILE — fictional person, not real data.',
        '## Generated for genome-lens functional testing. rsids rs3000000000+ are fake.',
        '##',
        '"RSID","CHROMOSOME","POSITION","RESULT"',
    ]

    # Re-sort using the proper 4-tuple list
    all_4 = sort_snps(
        [(r[0], r[1], r[2], r[3], "") for r in kb_rows]
        + [(r[0], r[1], r[2], r[3], "") for r in filler_with_nocalls]
    )
    for rsid, chrom, pos, gt, _ in all_4:
        lines.append(f'"{rsid}","{chrom}","{pos}","{gt}"')

    path = os.path.join(outdir, "synthetic-myheritage.txt")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  MyHeritage: {path}  ({len(all_4):,} SNPs, ~2% no-calls)")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    outdir = os.path.join(os.path.dirname(__file__), "..", "samples")
    os.makedirs(outdir, exist_ok=True)
    print("Generating synthetic genome samples…")
    make_23andme(outdir)
    make_ancestry(outdir)
    make_myheritage(outdir)
    print("Done. Upload any file to genome-lens to test the full pipeline.")
